# MACHINE LEARNING (ML)

Explicação sobre o que está sendo desenvolvido...

In [ ]:
# Bibliotecas que serão utilizadas
import pandas as pd

In [22]:
# Carregamento da base de dados
df = pd.read_csv("vendas_aguas_LGPD_tratada.csv", delimiter=";")

df.head()

,id_cliente,dt_entrega,dt_semana,qtd_aguas_entregues,qtd_aguas_ticket,obs_pedido,dt_estacao,dt_ano,dt_mes,cli_dias_desde_ultimo_pedido,cli_intervalo_medio,cli_frequencia_pedidos,cli_media_aguas_por_pedido,cli_total_pedidos,target_dt_proxima_compra,target_dias_ate_recompra,target_vai_comprar_15d
0,89,2023-01-02,Segunda,1,03/03,NaN,Verão,2023.0,1.0,0,5.91,1,1.01,1,2023-01-11,9,1
1,102,2023-01-02,Segunda,1,0,NaN,Verão,2023.0,1.0,0,NaN,1,1.00,1,NaN,0,0
2,120,2023-01-02,Segunda,2,0,NaN,Verão,2023.0,1.0,0,14.07,1,1.93,1,2023-01-18,16,0
3,50,2023-01-02,Segunda,2,0,NaN,Verão,2023.0,1.0,0,7.80,1,2.03,1,2023-01-09,7,1
4,8,2023-01-02,Segunda,1,07/10,NaN,Verão,2023.0,1.0,0,6.15,1,1.00,1,2023-01-06,4,1

## 1º - Tratamento da base de dados para ML

O QUE SERÁ REALIZADO E O POR QUE...

In [23]:
df_ml = df.copy()

### A) Transformação da variável "obs_pedido" em binário

In [24]:
# Conferência da variável
df_ml['obs_pedido']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
3102    NaN
3103    NaN
3104    NaN
3105    NaN
3106    NaN
Name: obs_pedido, Length: 3107, dtype: object

In [25]:
# Transformação de valores nulos para 0 e valores não nulos para 1
df_ml['obs_pedido'] = df_ml['obs_pedido'].notnull().astype(int)

In [26]:
# Verificação da transformação
df_ml['obs_pedido'].unique()

array([0, 1])

In [27]:
# Verificação da variável
df_ml['obs_pedido']

0       0
1       0
2       0
3       0
4       0
       ..
3102    0
3103    0
3104    0
3105    0
3106    0
Name: obs_pedido, Length: 3107, dtype: int64

### B) Transformação da variável "dt_semana" com One-Hot Encoding

In [ ]:
# Conferência dos dados da variável
df_ml['dt_semana'].unique()

array(['Segunda', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Terça',
       'Segunda ', 'Domingo'], dtype=object)

In [31]:
# Limpeza de dados (como espaços em branco antes e depois do texto)
df_ml['dt_semana'] = df_ml['dt_semana'].str.strip()

In [32]:
# Aplicação do One-Hot Encoding e remoção da coluna original
df_ml = pd.get_dummies(df_ml, columns=['dt_semana'], dtype=int)

In [ ]:
# Verificação da aplicação do One-Hot Encoding
df_ml.head()

,id_cliente,dt_entrega,qtd_aguas_entregues,qtd_aguas_ticket,obs_pedido,dt_estacao,dt_ano,dt_mes,cli_dias_desde_ultimo_pedido,cli_intervalo_medio,...,target_dt_proxima_compra,target_dias_ate_recompra,target_vai_comprar_15d,dt_semana_Domingo,dt_semana_Quarta,dt_semana_Quinta,dt_semana_Segunda,dt_semana_Sexta,dt_semana_Sábado,dt_semana_Terça
0,89,2023-01-02,1,03/03,0,Verão,2023.0,1.0,0,5.91,...,2023-01-11,9,1,0,0,0,1,0,0,0
1,102,2023-01-02,1,0,0,Verão,2023.0,1.0,0,NaN,...,NaN,0,0,0,0,0,1,0,0,0
2,120,2023-01-02,2,0,0,Verão,2023.0,1.0,0,14.07,...,2023-01-18,16,0,0,0,0,1,0,0,0
3,50,2023-01-02,2,0,0,Verão,2023.0,1.0,0,7.80,...,2023-01-09,7,1,0,0,0,1,0,0,0
4,8,2023-01-02,1,07/10,0,Verão,2023.0,1.0,0,6.15,...,2023-01-06,4,1,0,0,0,1,0,0,0

### C) Imputar a mediana para a variável "cli_intervalo_medio" com valores faltantes

### D) Exclusão das variáveis "arget_dt_proxima_compra" e "target_dias_ate_recompra"

### E) Exclusão da variável "cli_frequencia_pedidos"